### ISSUE TITLE
0.12.0 breaks the ToC in notebooks

### ISSUE THREAD

**Issue by Dukestep** [danielfrg/mkdocs-jupyter#10]
When deploying a Jupyter notebook with mkdocs `1.1.2` and and mkdocs-jupyter `0.12.0` the ToC does not render properly.

![image](https://user-images.githubusercontent.com/2139901/83018310-11a33780-9ff3-11ea-8ee4-f0f818a06584.png)

Rolling back to  mkdocs-jupyter `0.11.0` resolves the issue.

**Comment by danielfrg** [comment]
Thanks for the reports, ill take a look when i have some time!

**Comment by Sayam753** [comment]
Same issue here. Also I would like to mention that ToC is not working as expected in version 0.11.0. It is rendered well but fails to keep track of current reading position. And always the last section of ToC is highlighted. Is this the expected behaviour in version 0.11.0?

**Comment by danielfrg** [comment]
I think this was mostly an issue with `mkdocs 1.1.0` and one small change they made on an internal function. It has been fixed on: https://github.com/danielfrg/mkdocs-jupyter/commit/3896cb32ab4ae558a3cf55aa2dd0768416a43a34

Closing now, thanks for the reports!
Let me know other questions or issues you find.

**Comment by danielfrg** [comment]
Forgot to mention that there is indeed something weird with the material theme where the last item of the TOC is always selected.

This doesn't happen with the default theme so I think there is something related to that. I will try to research and see what can i find.
