### ISSUE TITLE
Embedding Jupyter Cells into existing Markdown Files

### ISSUE THREAD

**Issue by fgebhart** [danielfrg/mkdocs-jupyter#101]
Thanks for this great tool!

I'm currently playing around with it and would love to accomplish the following:
I have a bunch of `.md` files within my `docs/` folder which are rendered as expected. Within those `.md` files I'm making use of the markdown metadata section e.g.
```markdown
---
title: some title
description: some description
comments: true
tags:
  - python
  - pandas
---

## some other title
some markdown text here
```
Now I want to leverage mkdocs-jupyter to embed a jupyter notebook/cells into the given `.md` files in order to make use of the existing metadata and the entire flexibility I have with e.g. mkdocs-material (e.g. Admonitions, Diagrams, Formatting, ...).

Any idea if this is somehow feasible? Thanks in advance!

**Comment by danielfrg** [comment]
You should be able to have mkdocs-material markdown syntax inside the jupyter notebook markdown cells. Adding Jupyter notebook cells to .md cells is not possible.

**Comment by joseale2310** [comment]
Hi @fgebhart, you could write an admonition like this, if you are interested:

```
<div class="admonition note">
    <p class="admonition-title">Title of the admonition</p>
    <p> Lore ipsum<br>
        List example<br>
        &emsp;1. List item 1<br>
        &emsp;2. List item 2<br>
   </p>
</div>
```

**Comment by danielfrg** [comment]
I dont see how we can support adding cells to MD files with out some hacks so for now its only full notebook page. It does have the disadvantage of metadata but we could solve that in other ways.
