### ISSUE TITLE
Can we add caching between compilations?

### ISSUE THREAD

**Issue by Dref360** [danielfrg/mkdocs-jupyter#102]
Hello!

It currently takes ~10 seconds to run `nbconvert` on all our notebooks. I need to compile often when editing parts of the documentation using `mkdocs serve`.

Do you think it would make sense to cache the resulting markdown files between compilations?

With a bit of guidance, I can add this feature if you agree that it would be valuable.
Thanks!

**Comment by danielfrg** [comment]
Yes, it's been on my backlog for a while because it gets very annoying.

It should not be that difficult by looking at the notebook modified time, most of the work (if not all) should be on https://github.com/danielfrg/mkdocs-jupyter/blob/main/mkdocs_jupyter/plugin.py

**Comment by Dref360** [comment]
Hmm seems like `mkdocs build --dirty` does the trick. Sorry for the trouble.
