### ISSUE TITLE
Allow option to disable copy-clipboard functionality and enable RequireJS back

### ISSUE THREAD

**Issue by RaczeQ** [danielfrg/mkdocs-jupyter#103]
A while back there was issue #21 about RequireJS in notebooks.
Since #47, RequireJS has been removed and any attempt to bring it back results in a conflict between those two.

Is there any option (like in jupyter-flex) to somehow enable RequireJS?

https://github.com/danielfrg/mkdocs-jupyter/blob/98617201d891d46de7f734ab81b249913d77e29c/mkdocs_jupyter/templates/mkdocs_html/notebook.html.j2#L10-L27

**Comment by danielfrg** [comment]
Fixed in https://github.com/danielfrg/mkdocs-jupyter/commit/fb344fdc469e3abe1b931d0fdb6e62d17bc5f8c5
