### ISSUE TITLE
mkdocs-jupyter does not play well with squidfunk's material theme

### ISSUE THREAD

**Issue by sg-s** [danielfrg/mkdocs-jupyter#105]
specifically, [admonitions](https://squidfunk.github.io/mkdocs-material/reference/admonitions/) don't work at all (within notebooks)

**Comment by danielfrg** [comment]
I try to make it compatible but indeed any markdown things that are mkdocs specific and not supported by Jupyter itself won't work.

I will add a note to the README.

**Comment by forman** [comment]
Hi there! Is there anything additional that need to be configured to make admotions work? For me the style classes have no effect. Just plain text is rendered. Using latest pip package.
