### ISSUE TITLE
Safari not rendering pandas Dataframes properly

### ISSUE THREAD

**Issue by vstenby** [danielfrg/mkdocs-jupyter#115]
Hi!

I've been using mkdocs-jupyter to show Jupyter notebooks, but noticed that on my webpage, it doesn't render properly. It's the same issue with your demo ([https://mkdocs-jupyter.danielfrg.com/demo-nb/](https://mkdocs-jupyter.danielfrg.com/demo-nb/)).

macOS Monterey (12.5.1), , Safari Version 15.6.1 (17613.3.9.1.16)

<img width="1432" alt="Skærmbillede 2022-12-21 kl  10 13 36" src="https://user-images.githubusercontent.com/35364024/208867700-f349238f-3aaa-4bbb-a5f4-22cbd2c015f5.png">

iPadOS 16, Safari

![IMG_6A929EF3E89A-1](https://user-images.githubusercontent.com/35364024/208868409-305c6b76-5e44-4960-8475-8e61d114acb3.jpeg)

If I use nbconvert to convert a local notebook to HTML and open it in Safari on my Mac, the problem is gone.

<img width="1432" alt="Skærmbillede 2022-12-21 kl  10 18 02" src="https://user-images.githubusercontent.com/35364024/208868927-6bdc62ba-53f2-47ff-bc22-878065b839b2.png">

I therefore might think it's a problem with mkdocs-jupyter.

**Comment by vstenby** [comment]
Note: It is not a problem in Google Chrome.

**Comment by yeemh** [comment]
it's also problem in mobile chrome. (used iphone13 pro to test)
![IMG_0104](https://user-images.githubusercontent.com/51910605/209627003-5b3ba7e9-7c5d-4547-9aee-90c15403ab42.jpg)

and I solved this problem by changing css.
you can do it in extras/*.css
```css
.jupyter-wrapper table.dataframe {
  table-layout: auto !important;
}
```

or you can use overrides/html (I used this way)
```html
{% extends "base.html" %}

{% block content %}
{% if page.nb_url %}
    <a href="{{ page.nb_url }}" title="Download Notebook" class="md-content__button md-icon">
        {% include ".icons/material/download.svg" %}
    </a>
{% endif %}

{{ super() }}

<style>
    .jupyter-wrapper table.dataframe {
        table-layout: auto;
    }
</style>
{% endblock content %}
```

**Comment by vstenby** [comment]
This fixes it @yeemh - great find, thanks!

Seeing as this might be the desired default setting of the user, maybe we should make a PR?

**Comment by yeemh** [comment]
But the solution is not in mkdocs-jupyter, so I'm not sure it's okay to make a PR.
