### ISSUE TITLE
mkdocs-jupyter incompatible with mkdocs-material 9.0.0

### ISSUE THREAD

**Issue by HuangFuSL** [danielfrg/mkdocs-jupyter#117]
Hi, I'm using `mkdocs-jupyter` and `mkdocs-material` to build my personal blog. Recently mkdocs-material published a new `9.0.0` release. However, `mkdocs-jupyter` seems to be incompatible with the new version. When executing `pip install -r requirements` in my ci workflow, it reports that:

```log
ERROR: Cannot install -r requirements.txt (line 10) and mkdocs-material==9.0.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested mkdocs-material==9.0.0
    mkdocs-jupyter 0.22.0 depends on mkdocs-material<9.0.0 and >=8.0.0
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

My `requirements.txt` is as follows:

```
wheel
mkdocs==1.4.2
neoteroi-mkdocs==1.0.0
mkdocs-awesome-pages-plugin==2.8.0
mkdocs-git-revision-date-localized-plugin==1.1.0
mkdocs-git-revision-date-plugin==0.3.2
mkdocs-material==9.0.0
mkdocs-material-extensions==1.1.1
mkdocs-macros-plugin==0.7.0
mkdocs-jupyter==0.22.0
pymdown-extensions==9.9
matplotlib==3.6.2
pandas==1.5.2
jupyter==1.0.0
requests==2.28.1
jieba==0.42.1
lxml==4.9.2
mkdocs-meta-descriptions-plugin==2.2.0
```

For more details, please check the following link:

* [Dependabot pull request](https://github.com/HuangFuSL/HuangFuSL.github.io/pull/93)
* [Failed ci workflow](https://github.com/HuangFuSL/HuangFuSL.github.io/actions/runs/3825347666/jobs/6508269110)

**Comment by danielfrg** [comment]
I will try to update when i have some free time.
Thanks for the report!

**Comment by thangckt** [comment]
I found some admonitions in mkdocs material cannot shown

**Comment by SongshGeo** [comment]
Request compatibility to mkdocs-material 9.0.0, too. :)

**Comment by danielfrg** [comment]
I am about to go on vacation but I have scheduled some time to work on the lib when i come back. Thanks for the patience.
