### ISSUE TITLE
Support nbconvert 7.2.9

### ISSUE THREAD

**Issue by Overboard** [danielfrg/mkdocs-jupyter#121]
My use case involves Jupyter notebooks that manipulate and show SVGs.

However, `nbconvert<7.0.0` cannot process SVG output.  See,  
https://github.com/jupyter/nbconvert/blob/main/CHANGELOG.md#700  
Specifically, https://github.com/jupyter/nbconvert/pull/1837

With pipenv, mkdocs-jupyter is installing nbconvert v6.5.4

```shell
pipenv graph
mkdocs-jupyter==0.22.0
    ...
    "clipped for brevity"
    ...
  - nbconvert [required: >=6.2.0,<7.0.0, installed: 6.5.4]
```

Force installing `nbconvert==7.2.9` of course results in #96

I'm assuming similar results for versions between 7.0.0 and 7.2.9 but in any case, support for the most recent would be ideal.

**Comment by josephmcasey** [comment]
I have a changeset that resolves this, and I am writing up the docs to open up a PR.
