### ISSUE TITLE
execute ignore files in multiple diretories

### ISSUE THREAD

**Issue by giswqs** [danielfrg/mkdocs-jupyter#129]
Currently, `execute_ignore` only accepts a string.

```text
plugins:
  - mkdocs-jupyter:
      execute_ignore: "folder1/abc.ipynb"
```

It would be great to support a list so that we can ignore files under multiple directories, something like this:

```text
plugins:
  - mkdocs-jupyter:
      execute_ignore: ["folder1/abc.ipynb". "folder2/xyz.ipynb"]
```

**Comment by josephmcasey** [comment]
Duplicate of https://github.com/danielfrg/mkdocs-jupyter/issues/119

**Comment by danielfrg** [comment]
Closing as duplicate
