### ISSUE TITLE
mkdocs version lower bound

### ISSUE THREAD

**Issue by giswqs** [danielfrg/mkdocs-jupyter#134]
`mkdocs-jupyter` requires `mkdocs>=1.4.2,<2`, which is basically the latest mkdocs version. Is it possible to change the mkdocs lower bound to `1.4.0`? There are some other mkdocs plugins that are incompatible with the latest mkdocs yet. I can't use mkdcos-jupyter with other mkdocs plugins together.

**Comment by josephmcasey** [comment]
**Workaround:**
Although this isn't a solution to the latest release, you should be able to find a much lower bound if you set your `mkdocs-jupyter` dependency to release `0.22.X`.

**Comment by josephmcasey** [comment]
**Triage:**

@giswqs , would you be able to provide your current environment requirements in addition to which dependencies you are using that have these dependency resolution problems?

**Comment by giswqs** [comment]
I would like to ignore execute of multiple flies. This feature is only available for mkdocs-jupyter v0.23.0
https://github.com/danielfrg/mkdocs-jupyter/issues/129

Here is my environment setup
https://github.com/giswqs/leafmap/blob/master/.github/workflows/docs.yml
https://github.com/giswqs/leafmap/blob/master/requirements_docs.txt

It appears that `mkdocs-git-revision-date-plugin` does not support mkdocs v1.4.2 yet. See
https://github.com/giswqs/leafmap/actions/runs/4427004116/jobs/7764004828#step:9:256

**Comment by giswqs** [comment]
Unless `mkdocs-jupyter` is using some latest features of mkdocs v1.4.2, I would suggest relaxing the mkdocs version lower bound a little bit, such as `v.1.4.0`. Not all other mkdocs plugins are up to date with mkdocs v1.4.2.

**Comment by danielfrg** [comment]
I am ok with that. Can you make a quick PR changing the deps in pyproject.toml?
