### ISSUE TITLE
execute ignore multiple files does not work

### ISSUE THREAD

**Issue by giswqs** [danielfrg/mkdocs-jupyter#136]
I tried the latest version of mkdocs-jupyter v0.23.1, and it seems the `execute_ignore` option does not accept a list.  

https://github.com/danielfrg/mkdocs-jupyter/issues/129

```text
execute_ignore:  ["workshops/*.ipynb", "notebooks/zz_notebook_template.ipynb"]
```
> ERROR    -  Config value 'plugins': Plugin 'mkdocs-jupyter' option 'execute_ignore': Expected type: <class 'str'> but received: <class 'list'>

**Comment by danielfrg** [comment]
This has not been fixed. #129 was closed as duplicate. I will also close this one.
I will try to fix some of this issues this weekend 🤞🏼
