### ISSUE TITLE
'plugins': The "mkdocs-jupyter" plugin is not installed

### ISSUE THREAD

**Issue by everndah** [danielfrg/mkdocs-jupyter#144]
Why do I get this error (See Below)  and I have installed mkdocs-jupyter. For this reason  the  run fails. 

![image](https://user-images.githubusercontent.com/66929420/233826696-5f4546b4-d98d-44a2-ab3a-bc3d9bc45a70.png)

**Comment by danielfrg** [comment]
Be sure you have the right python on your `PATH`.

**Comment by everndah** [comment]
Thanks for the reply sir . The commit [7ca3229](https://github.com/everndah/python_tutorials/commit/7ca322925a0ff0d8c2c19790f722cd914d36cda3) solved the issue.

Changed from;

`- run: mkdocs gh-deploy --force`
`- run: pip install mkdocs-jupyter`

To;

`- run: pip install mkdocs-jupyter`
`- run: mkdocs gh-deploy --force`
