### ISSUE TITLE
 DeprecationWarning: Jupyter is migrating its paths to use standard platformdirs

### ISSUE THREAD

**Issue by danerlt** [danielfrg/mkdocs-jupyter#148]
I received a DeprecationWarning when using mkdocs-jupyter.

version info:
```
mkdocs==1.4.2
mkdocs-material==9.1.6
mknotebooks==0.7.1
mkdocs-jupyter==0.24.1
```
The DeprecationWarning  as follows:
```
INFO     -  DeprecationWarning: Jupyter is migrating its paths to use standard platformdirs
given by the platformdirs library.  To remove this warning and
see the appropriate new directories, set the environment variable
`JUPYTER_PLATFORM_DIRS=1` and then run `jupyter --paths`.
The use of platformdirs will be the default in `jupyter_core` v6
  File "D:\ProgramData\Anaconda3\envs\docs\Lib\site-packages\jupyter_core\utils\__init__.py", line 89, in deprecation
    warnings.warn(message, DeprecationWarning, stacklevel=stacklevel + 1)
  File "D:\ProgramData\Anaconda3\envs\docs\Lib\site-packages\jupyter_client\connect.py", line 20, in 
    from jupyter_core.paths import jupyter_data_dir, jupyter_runtime_dir, secure_write
```

```
INFO     -  DeprecationWarning: defusedxml.cElementTree is deprecated, import from defusedxml.ElementTree instead.
  File "D:\ProgramData\Anaconda3\envs\docs\Lib\site-packages\mkdocs_jupyter\convert.py", line 16, in add_anchor_lower_id
    from defusedxml import cElementTree as ElementTree
  File "D:\ProgramData\Anaconda3\envs\docs\Lib\site-packages\defusedxml\cElementTree.py", line 38, in <module>
    warnings.warn(
```

**Comment by cpnielsen** [comment]
@danielfrg Any idea when the next release will be?

**Comment by danielfrg** [comment]
I think this should be release

**Comment by cpnielsen** [comment]
@danielfrg The latest release was v0.24.1 on the 22nd of March - this was merged in after: https://github.com/danielfrg/mkdocs-jupyter/compare/0.24.1...main

**Comment by danielfrg** [comment]
I just made a new release that should include this fix.

**Comment by blaylockbk** [comment]
Hi! I'm still seeing this warning...
```
INFO    -  DeprecationWarning: Jupyter is migrating its paths to use standard platformdirs
           given by the platformdirs library.  To remove this warning and
           see the appropriate new directories, set the environment variable
           `JUPYTER_PLATFORM_DIRS=1` and then run `jupyter --paths`.
           The use of platformdirs will be the default in `jupyter_core` v6
             File "/users/blaylock/miniconda3/envs/mkdocs/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 90, in
           deprecation
               warnings.warn(message, DeprecationWarning, stacklevel=stacklevel + 1)
             File "/users/blaylock/miniconda3/envs/mkdocs/lib/python3.11/site-packages/jupyter_client/connect.py", line 22, in
               from jupyter_core.paths import jupyter_data_dir, jupyter_runtime_dir, secure_write
```

My versions
```
mkdocs-jupyter            0.24.6
mkdocs-material           9.4.6
```

Am I missing something?

**Comment by simonwei97** [comment]
I have same problem. 

```
mkdocs-jupyter             0.24.7      Use Jupyter in mkdocs websites
mkdocs-material            9.5.26      Documentation that simply works
```

That logs mean `jupyter_core` **v6** will set platformdirs as default, while in this repo dependencies, `jupyter-core` version is `5.7.2`. This version is  latest one. [jupyter_core Releases](https://github.com/jupyter/jupyter_core/releases.) 

Would we ignore this log info? Then following the log tips, set the environment variable `JUPYTER_PLATFORM_DIRS=1` and then run `jupyter --paths`.

---
**Refer**

- https://github.com/jupyter/jupyter_core/issues/398
- requirement in this repo:
  - https://github.com/danielfrg/mkdocs-jupyter/blob/main/requirements-dev.lock#L135
  - https://github.com/danielfrg/mkdocs-jupyter/blob/main/requirements.lock#L76

**Comment by liquidcarbon** [comment]
Started getting those warnings when just running tests on a skeleton package.

Oddly, they appear/disappear in response to just this line:
`from loguru import logger`
Tried to disable jupyter_core or jupyter_client but no luck yet.

**Comment by DeaMariaLeon** [comment]
I have the same warning. @danielfrg would you have any advice on this? 
BTW: Thank you for creating this project. :-)
