### ISSUE TITLE
admonition support

### ISSUE THREAD

**Issue by hkennyv** [danielfrg/mkdocs-jupyter#15]
Would it be possible to add support for [admonitions](https://python-markdown.github.io/extensions/admonition/) being rendered in markdown cells. I'd be happy to contribute to this too if needed

**Comment by Sayam753** [comment]
Hi @hkennyv 
The only way I rendered admonitions in mkdocs is to manually wrap the contents into html div tags and then, add suitable css classes. Checkout my blog post https://www.codingpaths.com/gsoc/variational-inference/.

As an example for admonition notes -
```html
<div class="admonition note">
    <p class="admonition-title">Observe</p>
    <p>contents</p>
</div>
```

**Comment by danielfrg** [comment]
Thats how I also do it. I dont think there is an easy way to add the mkdocs md way to the way jupyter converts.

**Comment by hkennyv** [comment]
gotcha, that makes a lot of sense. thank you both for the replies!
