### ISSUE TITLE
Feature: support `no_prompt`

### ISSUE THREAD

**Issue by fresh2dev** [danielfrg/mkdocs-jupyter#155]
I was looking for an option to show all input and output cells, but *not* show the `In[#]/Out[#]` cell numbers. I did not find such an option and ended up hiding the cell numbers/prompts with the CSS hack recommended here:

https://github.com/danielfrg/mkdocs-jupyter/issues/82#issuecomment-1403141027

Referencing the support and implementation of the `no_input` parameter, mkdocs-jupyter should also support a parameter `no_prompt` that hides the `In[#]/Out[#]` cell numbers without the need for CSS hacks.

https://nbconvert.readthedocs.io/en/latest/config_options.html

**Comment by bgriffen** [comment]
Would be great! I'd use it immediately.

**Comment by danielfrg** [comment]
Closing in favor of https://github.com/danielfrg/mkdocs-jupyter/issues/155
