### ISSUE TITLE
I need help - how to use mkdocs-jupyter in different dir than 'docs'?

### ISSUE THREAD

**Issue by Guilherme-Esplugues** [danielfrg/mkdocs-jupyter#160]
My .md files are in the default Mkdocs working directory, docs, but my notebooks are in another directory within the repository (outside of docs). Would there be any way to make this work?

Test using links, but I didn't succeed.

**Comment by deven-gqc** [comment]
The only way is to move your notebooks directory inside `docs`.

**Comment by danielfrg** [comment]
deven-gpc is correct.
