### ISSUE TITLE
release 0.24.3 sources on Pypi

### ISSUE THREAD

**Issue by Net-Mist** [danielfrg/mkdocs-jupyter#167]
Hello! Thanks for releasing version 0.24.3.

I've noticed that you have not released the sources on [pypi](https://pypi.org/project/mkdocs-jupyter/0.24.3/#files), whereas you did for [previous version](https://pypi.org/project/mkdocs-jupyter/0.24.2/#files).

Pypi sources are helpful for packaging this work on some linux distribution (for instance NixOS). Are you planning to continue to release them or are you dropping them?

Thanks a lot!

**Comment by danielfrg** [comment]
Weird, not sure why it didn't got uploaded yesterday but I just pushed the source.
Thanks for letting me know!
