### ISSUE TITLE
Unit-test fails on files on Pypi

### ISSUE THREAD

**Issue by Net-Mist** [danielfrg/mkdocs-jupyter#168]
Hello !
Why trying to run unit-tests on [files uploaded on pypi](https://files.pythonhosted.org/packages/b3/4f/cfad230c4d1e8e709ca2d1ef20a8e4d1a4fb72ee506fd6388b544b152cee/mkdocs_jupyter-0.24.3.tar.gz), the test `test_assets_included` fails because it can't find the files:

* mkdocs-jupyter.css
* mkdocs-jupyter.css.map
* mkdocs-jupyter.js

Is it expected ?

Thanks a lot !

**Comment by danielfrg** [comment]
I renamed the files to fix the themes but forgot to update that. I will try to fix it this weekend!

**Comment by Net-Mist** [comment]
Thanks a lot! Are you planing to update the files uploaded on pypi or release a new version soon ?

**Comment by danielfrg** [comment]
Yes, I am planning to do a bit more testing/cleanup and release a new version

**Comment by danielfrg** [comment]
I just made a new release that fixes the tests. Hopefully this helps!

**Comment by Net-Mist** [comment]
Hello!
Thanks a lot! Sadly the tests still fail using Pypi sources. It seems the folder `mkdocs_jupyter-0.24.4/src/mkdocs_jupyter/tests/mkdocs/docs` is not present in the tar.gz on pypi

**Comment by danielfrg** [comment]
Ok, just release one more version that fixes that.

**Comment by Net-Mist** [comment]
Thanks a lot! It now works :+1:
