### ISSUE TITLE
Bold text in notebook but not on website

### ISSUE THREAD

**Issue by mrdbourke** [danielfrg/mkdocs-jupyter#175]
Hey there! Big fan of the project, I use it for several of my tutorial-based websites.

Just a small note that may have been introduced in the last release, I've noticed bold/emphasised text appears in notebooks but not on the deployed version of the website.

This includes in the demo version of the website.

### Notebook (has bold text)

Link: https://github.com/danielfrg/mkdocs-jupyter/blob/main/demo/docs/demo-nb-md.ipynb 

<img width="594" alt="Screenshot 2023-10-12 at 11 58 51 am" src="https://github.com/danielfrg/mkdocs-jupyter/assets/16750345/e7484770-f76d-421d-bcc5-608a9c77eff6">

### Demo site (no bold text) 

Link: https://mkdocs-jupyter.danielfrg.com/demo-nb-md/#emphasis

<img width="692" alt="Screenshot 2023-10-12 at 11 59 06 am" src="https://github.com/danielfrg/mkdocs-jupyter/assets/16750345/1e450ac2-4cc8-4259-8cf1-051ea439039f">

---

This could potentially be a browser issue (Chrome) but I've noticed it on Safari as well.

I noticed this issue on my own project, the `<strong>` tags appear in the HTML but not on the docs website?

```
<blockquote>
<p><strong>Note:</strong> All of the steps in this notebook are focused on <a href="https://en.wikipedia.org/wiki/Supervised_learning"><strong>supervised learning</strong></a> (having data and labels). The other side of supervised learning is <a href="https://en.wikipedia.org/wiki/Unsupervised_learning"><strong>unsupervised learning</strong></a> (having data but no labels).</p>
</blockquote>
```

Link: https://github.com/mrdbourke/zero-to-mastery-ml/blob/9a15eea4ce4c9eefb1403e8aebace4360dcd1077/introduction-to-scikit-learn/index.html#L1390C1-L1392C14 

Docs website:

<img width="827" alt="Screenshot 2023-10-12 at 12 09 50 pm" src="https://github.com/danielfrg/mkdocs-jupyter/assets/16750345/57b2008c-5d09-4bb8-8fbe-44b656f6cc0b">

Link: https://dev.mrdbourke.com/zero-to-mastery-ml/introduction-to-scikit-learn/

**Comment by danielfrg** [comment]
Should be fix now in the latest version.

Thank you for the sponsor!
