### ISSUE TITLE
Latest release on PyPi has no associated `.tar.gz`

### ISSUE THREAD

**Issue by cwognum** [danielfrg/mkdocs-jupyter#197]
Hi @danielfrg, the conda-forge release of `v0.24.7` is failing, see https://github.com/conda-forge/mkdocs-jupyter-feedstock/pull/29. This seems to be happening because the latest `mkdocs` release on PyPi lacks a `.tar.gz` Source Distribution. Earlier versions do have such a source distribution.

This is causing downstream errors because `mkdocs-jupyter <0.24.7` is incompatible with `mkdocs >=1.6.0`. A simple workaround is to install the latest version of `mkdocs-jupyter` over `pip`, but it would be great if this can be fixed soon. 

<details><summary>Screenshot</summary>
<p>

![image](https://github.com/danielfrg/mkdocs-jupyter/assets/28000055/9e683eb4-98ad-41ef-a986-ec0d3c739a5e)

</p>
</details>

**Comment by cwognum** [comment]
@danielfrg Could you explain if this was intentional or accidental (e.g. you forgot to run `pnpm run build`)? If the `.tar.gz` Source Distribution will by missing from PyPi from now on, I will look into updating the conda-forge release process to generate the missing files. It seems we would just need to run `vite build` by running the build script of `package.json` (with `pnpm` or the like).

In case of the latter, it would be helpful to better understand how the package is released. Looking into [`RELEASE.md`](https://github.com/danielfrg/mkdocs-jupyter/blob/main/RELEASE.md) and [`Taskfile.yml`](https://github.com/danielfrg/mkdocs-jupyter/blob/main/Taskfile.yml), it seems you use `rye` to build and release the Python package, paired with `pnpm` (& `vite`) to build the web assets. How does `hatch` fit in?

**Comment by danielfrg** [comment]
It was accidental. I do use rye like you mentioned. I think hatch stuff is just there from the old way of building.

I should update the scripts to generate the .tar.gz too.

I'll try to take a look when I get some time.

**Comment by danielfrg** [comment]
that was my undestanding as well, that the tar.gz should be generated, maybe its then rye didnt upload it for some reason

**Comment by cwognum** [comment]
Hey @danielfrg, any update on the above?

**Comment by chuckwondo** [comment]
> Hey @danielfrg, any update on the above?

@danielfrg, I'm interested in getting this sorted out too. Thank you so much for your work on this extension!

**Comment by danielfrg** [comment]
Fixed on the latest version.

**Comment by cwognum** [comment]
Thanks @danielfrg ! 

Fixed for conda-forge with https://github.com/conda-forge/mkdocs-jupyter-feedstock/pull/35 as well.
