### ISSUE TITLE
Make MathJax-URL configurable

### ISSUE THREAD

**Issue by dr-br** [danielfrg/mkdocs-jupyter#199]
Hi,
I want to use mkdocs-jupyter with locally hosted MathJax (mkdocs-material +privacy plugin).
Unfortunately, nbconvert implicitly sets `mathjax_url`. In the template, which is part of mkdocs-jupyter (mkdocs_html &rarr; `{{ mathjax(resources.mathjax_url) }}`) this URL is used as well. When html.py is invoked, the URL is set implicitly.

Would it be possible, to configure a custom `mathjax_url`? Most conveniently in the mkdocs.yml.

Thanks in advance!

**Comment by danielfrg** [comment]
should be possible, are you interested in making a PR for that?

**Comment by danielfrg** [comment]
Fixed on your PR.
