### ISSUE TITLE
Following `Contributing.md` Leads to Failed Tests and Build

### ISSUE THREAD

**Issue by jpjon** [danielfrg/mkdocs-jupyter#204]
Following the `Contributing.md` file, I get build and test errors after creating a shell with 

`rye sync`

Follwing this directly from the file:

>Python:
>Run `mkdocs` in one of the tests configurations:
>- `cd mkdocs_jupyter/tests/mkdocs/`
>- `mkdocs serve -f material-with-nbs.yml`

also results in an error.

The error, which also occurs when running pytest, is as follows:

`jinja2.exceptions.TemplateNotFound: mkdocs_html/assets/index.css`

**Comment by danielfrg** [comment]
I just tried with no issues. You need to also run the JS section.
