### ISSUE TITLE
Request to Contribute New Functionality

### ISSUE THREAD

**Issue by jpjon** [danielfrg/mkdocs-jupyter#210]
Hi Daniel. 

Not sure how the best way to contact you is, but I wanted to create a new branch and push my added functionality of adding a "Download Data" button similar to the `include_source` configuration you have for downloading notebooks.

Can you please grant me collaborate status so I can create the appropriate PR?

**Comment by danielfrg** [comment]
You dont need to be a collaborator to submit a new PR. You can fork the repo and create a branch there. Then you can submit a PR to this repo.

Thanks for the interest!
