### ISSUE TITLE
Remove `_supported_extensions`

### ISSUE THREAD

**Issue by hodgestar** [danielfrg/mkdocs-jupyter#214]
Currently notebooks in formats other than `.py` or `.ipynb` cannot be processed even though because `_supported_extensions` is hard coded to allow only those two formats. Since the `include` list is configurable and by default allows exactly what `_supported_extensions` does, could `_supported_extensions` just be removed?

**Comment by danielfrg** [comment]
I think that should be ok unless its required by mkdocs which i think is the reason we have it.
Do you have notebooks in other formats?

**Comment by danielfrg** [comment]
oh ok that makes sense. i would have to try it. it would mean that all markdown files would be parsed by the extension and thats something want to keep options

**Comment by hodgestar** [comment]
I was hoping to implement something like `include: ["notebooks/*.md"]` in the config. Perhaps more is needed for that to work though?

**Comment by danielfrg** [comment]
This is being worked on here https://github.com/danielfrg/mkdocs-jupyter/pull/216

**Comment by hodgestar** [comment]
@danielfrg Yay! Should we perhaps close this as a duplicate of #215 which seems a much more complete feature request than my poor issue report here?
