### ISSUE TITLE
support for markdown with jupytext frontmatter?

### ISSUE THREAD

**Issue by tlambert03** [danielfrg/mkdocs-jupyter#215]
Apologies if I've missed a discussion elsewhere. 
I see that at the moment, the mkdocs plugin `should_include` method checks whether files have extensions either an `ipynb` or `py` extension.  Would you consider adding support for markdown files (perhaps gated on whether they have a jupytext frontmatter)?   I can contribute, but wanted to check how you felt about it first

**Comment by danielfrg** [comment]
i think that would be cool.

so it would parse markdown files as well and run the codecell?

**Comment by tlambert03** [comment]
yeah, works great.  I added:

- `supported_extensions = [".ipynb", ".py", ".md"]`
- `"include", config_options.Type(list, default=["*.py", "*.ipynb", "*.md"])`
- and then just changed the two `if extenion == '.py'` to `if extension in (".py", ".md"):`  in nbconvert2.py

the main question is probably going to be how to differentiate between a regular markdown file that should not be executed/included in mkdocs-jupyter formatting, and one that should be. looks like a naive `jupytext.read(file)` check *will* work fine with most markdown files, so we either need to pick a special key that should be present in the frontmatter, add a new config option to let people control it, or manually parse the markdown file to check if it contains frontmatter...

any thoughts/opinions there?

**Comment by psobolewskiPhD** [comment]
This would be very nice! 😍 
(Hi Talley, I seem to always run into you when looking for stuff!)
