### ISSUE TITLE
Confusing message about copying of files

### ISSUE THREAD

**Issue by znichollscr** [danielfrg/mkdocs-jupyter#219]
The `on_post_page` method [looks like the below.](https://github.com/danielfrg/mkdocs-jupyter/blob/d72a84a96d6a39cdf178c0d671d46b2b52f28aa9/src/mkdocs_jupyter/plugin.py#L151) prints a message about copying files. However, as far as I can tell, this method will copy the file without actually checking if the file is a notebook file or not. Hence, you get messages about files being copied, even though they're not actually notebook files. For example, you get messages like "Copied jupyter file: .../docs/changelog.md to .../site/changelog/changelog.md". As far as I can tell, these are misleading. The file being copied isn't a jupyter file, it's just a file. I'm not sure if the behaviour is correct either, should mkdocs-jupyter be doing this copying or is that really the responsibility of mkdocs, and mkdocs-jupyter should only be copying files that are actually related to notebooks?

**Comment by davidknight-seequent** [comment]
I've been wondering the same thing! Seems like a bug to me.

**Comment by danielfrg** [comment]
I think this is fixed by https://github.com/danielfrg/mkdocs-jupyter/pull/222

**Comment by znichollscr** [comment]
Super, thank you!

**Comment by danielfrg** [comment]
closing for now but reopen if this is still an issue!
