### ISSUE TITLE
Reintroduce `custom_mathjax_url` plugin arg

### ISSUE THREAD

**Issue by divya-layerhealth** [danielfrg/mkdocs-jupyter#223]
MathJax <= 2.7.9 has a [high-severity ReDoS vulnerability](https://github.com/advisories/GHSA-v638-q856-grg8).

To mitigate, at the very minimum we should upgrade the default MathJax version to v3.x. 

In addition, I noticed that PR https://github.com/danielfrg/mkdocs-jupyter/pull/201 introduced a `custom_mathjax_url` override, but that it was subsequently removed in PR https://github.com/danielfrg/mkdocs-jupyter/pull/211 -- was there a reason for this/should it be added back?

Happy to make both of these changes myself if that helps!

**Comment by danielfrg** [comment]
I dont think we had a real reason to remove it tbh. I think we should have it.

If you can get a PR that would be great!
