### ISSUE TITLE
How to change the font size of cells ?

### ISSUE THREAD

**Issue by folmos-at-orange** [danielfrg/mkdocs-jupyter#229]
That's it. Thanks in advance.

**Comment by danielfrg** [comment]
You can extend everything on the CSS of the website.

**Comment by folmos-at-orange** [comment]
Thanks! Should I change anything CSS specific of `mkdocs-jupyter`? Or of `mkdocs-material` ?

**Comment by danielfrg** [comment]
You can just extend the mkdocs-material CSS, they have docs for that.

**Comment by folmos-at-orange** [comment]
Thanks!
