### ISSUE TITLE
Add a copy button to each cell

### ISSUE THREAD

**Issue by AndrewEckart** [danielfrg/mkdocs-jupyter#23]
It would be great if there was a button to copy the content of each input or output cell (which probably requires a JS solution as described in [this SO answer](https://stackoverflow.com/a/44229929)).

Ideally, the solution would not be dependent on `mkdocs-material`. Currently some of the features of `mkdocs-jupyter` seem tightly coupled with `mkdocs-material`, such as the download button.

This plugin is really nice and painless to set up - thanks for developing it!

**Comment by danielfrg** [comment]
Thats a good suggestion, it should be doable, i will take a look eventually when i work on this.

And yes, its mostly coupled with `mkdocs-material` because its the theme I use and its almost impossible to have it working perfectly for multiple themes because of CSS things.
