### ISSUE TITLE
pointing to a jupyter notebook via relative path

### ISSUE THREAD

**Issue by sidhomj** [danielfrg/mkdocs-jupyter#27]
I'm making a docs page where I want one of my pages to point to a jupyter notebook in my repo.

right now, my yaml file reads as such:

```
nav:
    - Home: index.md
    - Getting Started: '../../tutorials/1 - Loading Data (Introduction).ipynb'
   
```

However, when trying to run the site, I get the following error:

```
 A relative path to '../../tutorials/1 - Loading Data (Introduction).ipynb' is included in the 'nav' configuration, which is not found in the documentation files
```

Any help would be appreciated to how to get this to work properly!

**Comment by danielfrg** [comment]
I think this is an mkdocs configuration issue more than the plugin, try adding the notebook file to a child directory instead of a parent one, i think mkdocs needs the files to structured that way.
