### ISSUE TITLE
 h2 (##) vs h1 (#) headers

### ISSUE THREAD

**Issue by hannorein** [danielfrg/mkdocs-jupyter#36]
Thanks for writing this plugin! Exactly what I needed. 

After reading the readme file, I can see that headers in a Jupyter notebook need to be h2 and not h1 to show up in the TOC. But I wonder why? Where is this limitation coming from and is there a way to change that? I'd like to avoid having to go through all my ipynb files to increasing the heading levels.

**Comment by danielfrg** [comment]
Yes, thats a "limitation" on how mkdocs handles the TOCs, we dont do anything special on this plugin just read the headers and pass them to mkdocs. Agree thats a bit annoying I have manually changed a lot of those for my docs :S

**Comment by hannorein** [comment]
Ah. That makes sense. Thanks. 

One more related question since I have you here: would it make sense to set the title attribute of the mkdoc page object to whatever nbconvert chooses as the title? I think that would be the first h1 header that appears in the file in most cases. Unless I'm missing something, mkdocs-jupyter is currently not setting any title attribute. So if I want to have a title that is different from the filename, I need to specify it manually when setting up the navigation.

**Comment by danielfrg** [comment]
Yes, I have noticed that. I am how that can be fixed but there must be a way, would you create another issue for that?
