### ISSUE TITLE
nb2html cannot convert notebooks with an embedded image

### ISSUE THREAD

**Issue by ChristopherMayes** [danielfrg/mkdocs-jupyter#40]
This works:
`jupyter nbconvert --to html has_image.ipynb` 

But the converter from this package:
```python
from mkdocs_jupyter.nbconvert2 import nb2html
nb2html('has_image.ipynb')
```
produces:
`AssertionError: missing attachment: image.png`

I've attached the notebook (zipped)

[has_image.ipynb.zip](https://github.com/danielfrg/mkdocs-jupyter/files/6595446/has_image.ipynb.zip)

Thank you for the great package!

**Comment by ChristopherMayes** [comment]
This line causes the problem:

https://github.com/danielfrg/mkdocs-jupyter/blob/02bf2dd6e37f4fb5df8beff54d09625b0d03d956/mkdocs_jupyter/nbconvert2.py#L50

**Comment by hhslepicka** [comment]
@danielfrg did you have a chance to look into this issue? Or do you know of a workaround that we could use?

**Comment by danielfrg** [comment]
All you need to do is to change put the images on the `docs` directory and change the path to be relative to that dir.
We actually have a test that does that - [notebook](https://github.com/danielfrg/mkdocs-jupyter/blob/main/mkdocs_jupyter/tests/mkdocs/docs/demo.ipynb) - [setup](https://github.com/danielfrg/mkdocs-jupyter/tree/main/mkdocs_jupyter/tests/mkdocs).

(sorry it took forever, thanks for using the lib and reporting the issue for future users!)

**Comment by hadim** [comment]
I am having the same issue. I would prefer to use the embedded images instead of having to copy them to the dir structure.

**Comment by hadim** [comment]
It works by commenting `"markdown2html": custom_markdown2html,`. Would that be possible to make it work? At least behind an option?
