### ISSUE TITLE
skip some notebooks being executed

### ISSUE THREAD

**Issue by giswqs** [danielfrg/mkdocs-jupyter#43]
When setting `execute: True` in `mkdocs.yml`, mkdocs-jupyter executes all notebooks under the `docs` directory. Is it possible to skip some notebooks during execution? For example, some notebooks might contain some interactive functions (e.g., `input()`) that require user input. Such notebooks will fail to execute. As a result, mkdocs fails to build.

**Comment by danielfrg** [comment]
Not possible at the moment, its all or nothing. It shouldn't be that hard to add another param as a wildcard to filter which nbs to execute.
