### ISSUE TITLE
TypeError: macro 'jupyter_widgets' takes not more than 2 argument(s)

### ISSUE THREAD

**Issue by giswqs** [danielfrg/mkdocs-jupyter#48]
It seems the new version has a bug. The same notebook works fine in the past (v0.17.3), but it is throwing an error now (v0.18.0). 

https://github.com/giswqs/leafmap/runs/3704421188?check_suite_focus=true
![image](https://user-images.githubusercontent.com/5016453/134756142-84e194a5-2f77-490a-9081-086511435bbc.png)

**Comment by danielfrg** [comment]
0.18.0 depends on nbconvert 6.2.0. You can fix it by just upgrading. I will make a new release to pin that dependency.

**Comment by danielfrg** [comment]
Oh actually its already pinned. I think you might just have to make it explicit on your requirements.txt to fix this issue.

Thanks for the report and pls reopen if you find something else.
