### ISSUE TITLE
Support for other languages than Python ?

### ISSUE THREAD

**Issue by fortierq** [danielfrg/mkdocs-jupyter#51]
Hi,
I tried to use mkdocs-jupyter with OCaml notebooks. However, the syntax highlighting is incorrect.
nbconvert works correctly though.
I guess I have to change the CSS. Do you have any advice ?

**Comment by danielfrg** [comment]
Thanks for the reports, it was just that we had python hardcoded since its the one I use the most.
I am reading now the kernel language name from the ipynb json so it should be fixed on #52.

**Comment by danielfrg** [comment]
Version `0.18.1` includes the fix. let me know if you find other issues.

**Comment by fortierq** [comment]
Great ! Thank you.

**Comment by fortierq** [comment]
Hum... In the notebooks I have, some of them don't have the language field in kernelspec. Only something like this : 
```
  "kernelspec": {
   "display_name": "Python 3.9.6 64-bit ('base': conda)",
   "name": "python3"
  },
``` 
I am adding them manually, but I wonder if this could be an issue with some IDE not adding those.

**Comment by danielfrg** [comment]
mmm it could be. The nbs I have have it. I added a test and it will default to python just in case.

**Comment by fortierq** [comment]
It looks like the code inside markdown cells (such as ```ocaml ... ```) are not highlighted correctly.  
For example : https://mp2i-fsm.github.io/mp2i-2021/1_ocaml/tp/tp1/

**Comment by danielfrg** [comment]
Mmm annoying... i bet those go through a different parser. I'll try to take a look.
