### ISSUE TITLE
Images are not included correctly

### ISSUE THREAD

**Issue by fortierq** [danielfrg/mkdocs-jupyter#53]
It looks like images included in notebooks are not displayed properly after using mkdocs.  
For example :   
https://github.com/mp2i-fsm/mp2i-2021/blob/main/0_intro/2_rendu_tp.ipynb contains 
```html
<img src=img/editor.png width=450>
```
which remains the same in the output https://github.com/mp2i-fsm/mp2i-2021/blob/gh-pages/0_intro/2_rendu_tp/index.html

However, a new folder is created, containing the .html but not the images (which are one directory up) : https://github.com/mp2i-fsm/mp2i-2021/tree/gh-pages/0_intro/2_rendu_tp

Therefore the images are not found : https://mp2i-fsm.github.io/mp2i-2021/0_intro/2_rendu_tp

Is it solvable easily? I can take a look if needed.

**Comment by fortierq** [comment]
Remark : I did not test with the standard way of including images in .ipynb (using markdown ![...](...)), maybe it works... But <img> is more flexible

**Comment by danielfrg** [comment]
This should work but you need to set a path relative to the mkdocs content, for example put the images in `docs/images/img.png`, then use `<img src="/images/img.png>`

**Comment by fortierq** [comment]
Indeed but it is not very handy: the path will not work when you open your notebook in Jupyter.  
mkdocs automatically modifies the path of each image to make it work.
I will try to add it to mkdocs-jupyter by regexp.

**Comment by danielfrg** [comment]
Yes, its not ideal to not see them in the NB.
It would be interesting to see if you can make it work with mkdocs tooling

**Comment by fortierq** [comment]
I solved it by automatically converting images in notebooks in base64.
