### ISSUE TITLE
Can't pip install repo

### ISSUE THREAD

**Issue by fortierq** [danielfrg/mkdocs-jupyter#55]
I am modifying a fork of this project but can't install it via pip & git :
```
pip install git+https://github.com/fortierq/mkdocs-jupyter.git
...
mkdocs gh-deploy --force
```
```
INFO     -  Converting notebook (execute=False): /home/runner/work/mp2i-2021/mp2i-2021/docs/0_intro/1_jupyter.ipynb
jinja2.exceptions.TemplateNotFound: mkdocs_html/assets/mkdocs-jupyter.css
```
`pip install git+https://github.com/danielfrg/mkdocs-jupyter.git` gives the same error message.  
Do you know where it comes from and how to solve it ? Is it mandatory to upload my fork on PyPI ?

**Comment by danielfrg** [comment]
You need to build the JS/CSS part of the project.

In the js directory run `npm install` `npm run build`

**Comment by fortierq** [comment]
It works, thank you.
