### ISSUE TITLE
Support mkdocs-material 8

### ISSUE THREAD

**Issue by astanziola** [danielfrg/mkdocs-jupyter#57]
Hi! First of all, thanks for the amazing package! :)

`mkdocs-material` has released version 8.0.x, however installing `mkdocs-jupyter` downgrades the `mkdocs-material` install to the latest 7.x version. Are there any plans to support the 8.0.x version of mkdocs-material?

**Comment by danielfrg** [comment]
Yes, its very likely it works already but I pin the packages to major versions.
Material 8 was just released so i will support it when I update my websites to it.

**Comment by danielfrg** [comment]
Version `0.19.0` is out with support for mkdocs-material 8.

**Comment by astanziola** [comment]
Thanks a lot for the super-speedy fix :smile:
