### ISSUE TITLE
Search bar disappears 

### ISSUE THREAD

**Issue by wroscoe** [danielfrg/mkdocs-jupyter#6]
When I add this plugin the search functionality is removed from the mkdocs site. Is this a known issue or something with my configuration.

**Comment by wroscoe** [comment]
Looks like i had to include the search plugin..

```
plugins:
    - search
    - mkdocs-jupyter
```

**Comment by Dukestep** [comment]
Experienced this issue as well with the `mkdocs` theme. Thanks for the fix.

Is this something that should just work out of to box without having to add the `search` plugin?

**Comment by Realvincentyuan** [comment]
Encountered into this, too with the 0.13 version as this is the only valid version in my company.

Adding `search` explicitly also does not work, the latest mkdocs-materials version is 8.2.19
