### ISSUE TITLE
Build does not fail even there is an error executing a notebook

### ISSUE THREAD

**Issue by giswqs** [danielfrg/mkdocs-jupyter#63]
Previously, the build would fail if there is an error executing a notebook. Recently, it seems the build continues even there are errors. Did mkdocs-jupyter recently make changes regarding this behavior? Is possible to force the build to fail if there are errors? I am not sure if this is a mkdocs-jupyter or mkdocs issue.

https://leafmap.org/notebooks/43_search_control/
![](https://i.imgur.com/jUTV7lh.png)

**Comment by danielfrg** [comment]
We haven't made any changes, it could be a change in ipython or ipykernel.
There should  be a param we can pass to those libraries to make it fail.

**Comment by giswqs** [comment]
Do you know what param could we pass to those libraries to make it fail?
