### ISSUE TITLE
Subtitles overlapping with notebook text

### ISSUE THREAD

**Issue by mrdbourke** [danielfrg/mkdocs-jupyter#68]
Hello,

I'm using mkdocs-jupyter to automatically turn a repo of Jupyter Notebooks into documentation.

It's working fantastic for 95% of my Jupyter Notebooks, however, there's two notebooks which are overlapping with the subtitles for some reason, see the example here:
<img width="1372" alt="Screen Shot 2022-02-04 at 8 19 24 am" src="https://user-images.githubusercontent.com/16750345/153996214-2dd4c7e6-292e-4df6-8708-614e8a193dc3.png">

The link to the documentation pictured above is here: https://dev.mrdbourke.com/tensorflow-deep-learning/09_SkimLit_nlp_milestone_project_2/

It seems to only be happening to notebooks in the "Natural Language Processing" heading on the left, I'm not sure why this would be as they are created in the same way as the rest of the notebooks (no issue).

The notebook source is available here:  https://github.com/mrdbourke/tensorflow-deep-learning/blob/main/09_SkimLit_nlp_milestone_project_2.ipynb

Any help or insight would be greatly appreciated.

**Comment by danielfrg** [comment]
Thanks for the links and source!

The issue on the page you posted is the code block `<pre>`. We should be able to fix it. I will try to take a look soon!

**Comment by mrdbourke** [comment]
Thank you :)

**Comment by mrdbourke** [comment]
Hey @danielfrg, any update on the fix for this?

I tried moving the nav to the left but the issue still occurs (in a slightly different way): 
<img width="2032" alt="Screen Shot 2022-03-24 at 12 40 47 pm" src="https://user-images.githubusercontent.com/16750345/159831357-9edf858c-94a0-4017-b3d9-59acafd17118.png">

Is there anything I could do to format things differently?
