### ISSUE TITLE
`ipython_genutils` dependency not found

### ISSUE THREAD

**Issue by vincentsarago** [danielfrg/mkdocs-jupyter#69]
I'm not sure what changed but my CI is failing right now with `ModuleNotFoundError: No module named 'ipython_genutils'` (see https://github.com/stac-utils/titiler-pgstac/runs/5538467483?check_suite_focus=true) 

https://github.com/danielfrg/mkdocs-jupyter/blob/e1af7f626b3ec363193788b466dec6f5122dea5c/mkdocs_jupyter/convert.py#L17

I'll try to dig deeper and open a PR 🙏

**Comment by vincentsarago** [comment]
ref: https://github.com/jupyter/nbconvert/issues/1725

**Comment by vincentsarago** [comment]
👋 @danielfrg, thanks for merging the PR 🙏 

Do you think it's possible to cut minor release with the fix?

I also realize that I didn't update the changelog, I'll be happy to do it if you want.

**Comment by danielfrg** [comment]
Yes, I will make a release ASAP. I should be able to do it later today!

**Comment by vincentsarago** [comment]
THANK YOU 🙏

**Comment by danielfrg** [comment]
Version `0.20.1` has been released!
