### ISSUE TITLE
nice tool, any configuration could hide python code, only display output?

### ISSUE THREAD

**Issue by leonyi168** [danielfrg/mkdocs-jupyter#81]
as the title.

thanks

**Comment by danielfrg** [comment]
Not currently but we should add an option to do that.

**Comment by oceanumeric** [comment]
I did something like this: https://oceanumeric.github.io/blog/2022/jupyter-style/

**Comment by mikegerber** [comment]
With `show_input: False` and `no_input: True` it does not include the inputs anymore.

**Comment by scottstanie** [comment]
Yeah the options are very close to what I want, but there doesn't seem to be an option for just doing `exclude_output_prompt=False` and `exclude_input_prompt=False` but  `exclude_input=False` so we see the input code.

https://github.com/ggbaro/mkdocs-jupyter/blob/1d0d859e4773bd6cc837a9f0cfb79eea5a8f76a1/mkdocs_jupyter/nbconvert2.py#L187

**Comment by danielfrg** [comment]
Closing in favor of #170
