### ISSUE TITLE
How to add tags on top of the template?

### ISSUE THREAD

**Issue by Realvincentyuan** [danielfrg/mkdocs-jupyter#84]
# Question
Looks like it does not have an explicit solution to add tags in the page rendered based on a Jupyter file, is there any workaround?

# Reference

- setting up tags in the mkdocs-material theme: https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags

**Comment by danielfrg** [comment]
Dup https://github.com/danielfrg/mkdocs-jupyter/issues/84
