### ISSUE TITLE
Unicode strings with encoding declaration are not supported.

### ISSUE THREAD

**Issue by tonylee2016** [danielfrg/mkdocs-jupyter#92]
ERROR    -  Error reading page 'xxxx/xxx.ipynb': Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.

its related to lxml

  File "src/lxml/etree.pyx", line 3254, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1908, in lxml.etree._parseMemoryDocument

**Comment by tonylee2016** [comment]
workaround: put # coding: utf-8 in the notebook

**Comment by tonylee2016** [comment]
I believe it is not related to package, closing the issue

**Comment by jayqi** [comment]
I ran into this issue as well. 

@tonylee2016 can you please clarify where you think this error is originating from? Is it nbconvert or lxml? I haven't found issues in any other projects that seem to be related to this.

**Comment by tonylee2016** [comment]
> 

its nbconvert, I think it calls lxml. In my case, one cell in my notebook is using [schemdraw](https://schemdraw.readthedocs.io/en/latest/). After I clear the output in that cell, it worked.

**Comment by tonylee2016** [comment]
> I ran into this issue as well.
> 
> @tonylee2016 can you please clarify where you think this error is originating from? Is it nbconvert or lxml? I haven't found issues in any other projects that seem to be related to this.

its nbconvert, I think it calls lxml. In my case, one cell in my notebook is using [schemdraw](https://schemdraw.readthedocs.io/en/latest/). After I clear the output in that cell, it worked.

**Comment by pjbull** [comment]
Looks like there was a partial fix here: https://github.com/jupyter/nbconvert/pull/1837
And finishing that is tracked here: https://github.com/jupyter/nbconvert/issues/1849

**Comment by craldaz** [comment]
I get this error when I try to run the demo. It occurs in the ruby.ipynb notebook. Removing it allows the demo to run.
