### ISSUE TITLE
TemplateNotFound: mkdocs_html/assets/mkdocs-jupyter.css

### ISSUE THREAD

**Issue by Tina0330** [danielfrg/mkdocs-jupyter#94]
running `python -m mkdocs gh-deploy` encountering the error like this:
![image](https://user-images.githubusercontent.com/86669014/184848650-30b8f3a7-ddbe-4833-a9fc-687ca638f9a5.png)
, and I checked my related package versions:

- mkdocs==1.3.1
- mkdocs-material==8.3.2
- mkdocs-jupyter==0.21.0
- jinja2==3.0.3

Could anyone help me look at this?

**Comment by craldaz** [comment]
I am getting the same error, downloaded repo, created environment from environments.yml, and installed from repo via `pip install -e .` and tried to build the demo docs

**Comment by josephmcasey** [comment]
**RCA: User Failure**

Summary: User has failed to use the javascript dependency webpack to transpile web app dependency. Resolved by running `cd js && npm install && npm run dev` which produces the following output

```
➜ npm run dev

> mkdocs-jupyter@1.0.0 dev
> webpack --mode=development --watch

asset mkdocs-jupyter.css 619 KiB [emitted] (name: main) 1 related asset
asset mkdocs-jupyter.js 2.42 KiB [emitted] (name: main) 1 related asset
Entrypoint main 622 KiB (694 KiB) = mkdocs-jupyter.css 619 KiB mkdocs-jupyter.js 2.42 KiB 2 auxiliary assets
runtime modules 274 bytes 1 module
modules by path ./src/styles/ 50 bytes (javascript) 619 KiB (css/mini-extract)
  ./src/styles/index.scss 50 bytes [built] [code generated]
  css ./node_modules/css-loader/dist/cjs.js!./src/styles/theme.css 28.5 KiB [built] [code generated]
  css ./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./src/styles/index.scss 591 KiB [built] [code generated]
./src/index.js 29 bytes [built] [code generated]
webpack 5.72.0 compiled successfully in 2302 ms
```

**Discovery Path**
Identified when attempting to make a contribution as a part of recommendations made in https://github.com/danielfrg/mkdocs-jupyter/issues/125

**Resolution**
If you run into this issue make sure you have a seperate terminal running the following:
```
cd js
npm install
npm run dev
```

**Comment by danielfrg** [comment]
Thanks for figuring this one out.

**Comment by Anselmoo** [comment]
@danielfrg it looks like that with the latest developer version of mkdocs-jupyter, the `mkdocs-jupyter.css` is still missing for jinja2.

```terminal
jinja2.exceptions.TemplateNotFound: mkdocs_html/assets/mkdocs-jupyter.css
```

**Comment by danielfrg** [comment]
By dev version you mean if you clone the repo?
If yes, then you have to build the `js` package using `npm` to build the styles. The built output are not included in the source.

**Comment by Anselmoo** [comment]
@danielfrg thx for the feedback.

Exactly, `mkdocs-jupyter = {git = "https://github.com/danielfrg/mkdocs-jupyter.git"}` that's the confit in `pyproject.toml`.

**Comment by danielfrg** [comment]
Got it. I thought it was on the built package.
On that case you need to build the `js` package.

```
npm install
npm build
```

should do it
