### ISSUE TITLE
jinja2.exceptions.TemplateNotFound: basic.tpl

### ISSUE THREAD

**Issue by giswqs** [danielfrg/mkdocs-jupyter#96]
Ran into this issue. Any advice?

- mkdocs-1.3.1 
- mkdocs-jupyter-0.13.0
-  mkdocs-material-8.2.11

https://github.com/giswqs/geospatial/runs/8005207114?check_suite_focus=true
![image](https://user-images.githubusercontent.com/5016453/186534149-0d7b4615-1c9e-406f-8b64-8a9ad6d3e989.png)
![image](https://user-images.githubusercontent.com/5016453/186534060-d135fa1e-638c-4e86-bc75-b4a2eca46040.png)

**Comment by vincentsarago** [comment]
I'm getting the same error when trying to generate titiler documentations https://github.com/developmentseed/titiler/runs/8014258687?check_suite_focus=true There seems to be a version conflicts somewhere in either mkdocs-jupyter or nbconvert 🤷

**Comment by vincentsarago** [comment]
Update: if you force `nbconvert==6.5` then it works well 

https://github.com/developmentseed/titiler/blob/master/.github/workflows/deploy_mkdocs.yml#L33
