### ISSUE TITLE
Documenting functions

### ISSUE THREAD

**Issue by srush** [danielfrg/mkdocs-jupyter#97]
Thanks for the amazing library. 

We're using it to document the chalk-diagrams project https://chalk-diagrams.github.io/api/shapes/#polygons and the notebook format is amazing for joining code and docs. 

However I was curious if there is a better way to document functions. Currently I'm calling out to render them in html. But it feels a bit ugly. Is it at all possible to intersect with mkdocstrings? Does the markdown go through the mkdocs pipeline at all?

CC @danoneata

**Comment by cory-kinney** [comment]
I've been have the same issues, specifically I would love to use mkdocstrings' cross-references functionality to link documentation like `[full.path.object][]`. This could be related to #105 as well, as it seems the output of mkdocs-jupyter doesn't get any further processing with how the pipeline is set up.

**Comment by danielfrg** [comment]
It goes out of the scope of the project
