### ISSUE TITLE
How to include notebooks located outside of the docs folder?

### ISSUE THREAD

**Issue by hugolytics** [danielfrg/mkdocs-jupyter#98]
I put all my notebooks in a /notebooks folder, since we usually use notebooks non exclusively for documentation purposes.
So how can i specify in the mkdocs.yml the path to my notebook?
I've tried

  - mkdocs-jupyter:
      include: ["./notebooks/*.ipynb"]

and
nav:
   - Example:./notebooks/my_notebook.ipynb

however, i can't seem to tell mkdocs-jupyter to use this path.

**Comment by theorashid** [comment]
Try using a symbolic link from the docs folder back to the notebooks folder. Like [this](https://github.com/thomaspinder/GPJax/tree/master/docs).

I haven't tested it, but from the docs folder, something like:

`ln -sr ../notebooks examples`

will create a link in the docs folder back to notebooks. Then you can specify:
```
nav:
     - Examples:
          - Insightful notebook: examples/a_notebook.ipynb
```

**Comment by danielfrg** [comment]
I agree it would be nice but we cant support this because mkdocs requires the source files to be in the `docs` folder.

If they lift that requirement we can revisit this.
